### ISSUE TITLE
Check for missing server configuration?

### ISSUE THREAD

**Issue by francoism90** [Hi-Folks/lara-lens#7]
Thanks, I was looking for something like this and will try it later this week.

Would it be possible to diagnose for missing PHP packages, OS packages, etc. as well?
I don't know if this is possible without `root` and if this out of the scope of this package? :)

**Comment by roberto-butti** [comment]
Hi @francoism90 , I'm working on something like this 🚀 🥳  :
<img width="795" alt="Screenshot 2020-08-12 at 10 27 44" src="https://user-images.githubusercontent.com/678434/89993150-931b7500-dc86-11ea-9b91-f468b0a4ea2b.png">

**Comment by roberto-butti** [comment]
I'm testig a little bit where some PHP extensions are missing:
<img width="938" alt="Screenshot 2020-08-12 at 11 20 00" src="https://user-images.githubusercontent.com/678434/89998495-ee9d3100-dc8d-11ea-9525-da20ddaa21e6.png">

**Comment by roberto-butti** [comment]
<img width="798" alt="Screenshot 2020-08-30 at 15 55 52" src="https://user-images.githubusercontent.com/678434/91660969-54d0e300-ead9-11ea-83c4-59dd4b38cb53.png">
Including some Server requirements check in v0.1.17:
- php version required
- list of PHP modules required

We follow the official doc for:
- Laravel 6 : https://laravel.com/docs/6.x/installation#server-requirements
- Laravel 7 : https://laravel.com/docs/7.x/installation#server-requirements
- Laravel 8 : https://laravel.com/docs/master/installation#server-requirements (now, 8 is in master because is not yet released)
